const DISPLAY_ALERT = 'SHOW_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';
const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
const SETUP_USER_ERROR = 'SETUP_USER_ERROR';
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const LOGOUT_USER = 'LOGOUT_USER';
const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
const HANDLE_CHANGE = 'HANDLE_CHANGE';
const CLEAR_VALUES = 'CLEAR_VALUES';
const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN';
const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';
const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN';
const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';

export {
  DISPLAY_ALERT,
  CLEAR_ALERT,
  SETUP_USER_BEGIN,
  SETUP_USER_SUCCESS,
  SETUP_USER_ERROR,
  TOGGLE_SIDEBAR,
  LOGOUT_USER,
  UPDATE_USER_BEGIN,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_ERROR,
  HANDLE_CHANGE,
  CLEAR_VALUES,
  CREATE_JOB_BEGIN,
  CREATE_JOB_SUCCESS,
  CREATE_JOB_ERROR,
  GET_JOBS_BEGIN,
  GET_JOBS_SUCCESS,
};
