const DISPLAY_ALERT = 'SHOW_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';
const SETUP_USER_BEGIN = ' SETUP_USER_BEGIN';
const SETUP_USER_SUCCESS = ' SETUP_USER_SUCCESS';
const SETUP_USER_ERROR = ' SETUP_USER_ERROR';
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const LOGOUT_USER = 'LOGOUT_USER';

export {
  DISPLAY_ALERT,
  CLEAR_ALERT,
  SETUP_USER_BEGIN,
  SETUP_USER_SUCCESS,
  SETUP_USER_ERROR,
  TOGGLE_SIDEBAR,
  LOGOUT_USER,
};
